export const GOVERNANCE_CONTRACT_ID =
  "LkfzZvdl_vfjRXZOPjnov18cGnnK3aDKj0qSQCgkCX8";
export const TREASURY_CONTRACT_ID =
  "Gj5peOLt14Mi9ARipHg9Vml3JK5Kebz5TaMGXdRgNUo";
export const POOL_SOURCE_CONTRACT_ID =
  "slRfB7WKAEQb5SiO7e-G_FWoAZ4LkoyAYE31ToPXTV8";
